[package]
name = "hycc_resolution"
version = "0.1.0"
edition = "2024"

[dependencies]
hycc_diagnostic = { path = "../hycc_diagnostic" }
hycc_hir = { path = "../hycc_hir" }
hycc_scope = { path = "../hycc_scope" }
hycc_span = { path = "../hycc_span" }
hycc_symbol = { path = "../hycc_symbol" }
hycc_util = { path = "../hycc_util" }
